### PR TITLE
fix(rxCharacterCount): Clean up the generated elements

### LINKED ISSUE #847: rxCharacterCount doesn't clean up when bound element is removed
If the input or textarea is removed from the dom (say, via an ng-if) the character count stays visible.

### PR DESCRIPTION
**Pull request by parlarjb**
Closes #847

Properly clean up the character count and other generated elements,
created when rx-character-count is used on an element.

This also moves the character count into the `.counted-input-wrapper`
div. Previously it sat outside of it.

BREAKING CHANGE
We've removed the `.character-count-wrapper` class. Previously we
set widths on this class. It ended up being redundant, widths
should now be set w.r.t. `.counted-input-wrapper`

### CODE REVIEW

**Comment by comeatmebro** [comment]
[Wraith UI diff](http://eb4d4842ea70055541c8-b6a3ba129b5eb76af13f4d17e4c1a53b.r51.cf5.rackcdn.com/856/gallery.html)

File: src/rxCharacterCount/rxCharacterCount.js [hunk 1]
```diff
@@ -1,12 +1,32 @@
 angular.module('encore.ui.rxCharacterCount', [])
 .directive('rxCharacterCount', function ($compile) {
-    var counter = '<div class="character-countdown" ' +
-                  'ng-class="{ \'near-limit\': nearLimit, \'over-limit\': overLimit }"' +
+    var counterStart = '<div class="character-countdown" ' ;
```
Comment (megalord) [inline src/rxCharacterCount/rxCharacterCount.js]: Looks like there is an extra space right before the `;` at the end of the line. :grin:

File: src/rxCharacterCount/rxCharacterCount.spec.js [hunk 2]
```diff
@@ -120,6 +122,44 @@ describe('rxCharacterCount', function () {
...
+        });
+        
+        it('should hide the character count if the element hides (ngHide)', function () {
+            parentDiv = helpers.createDirective(ngHideTemplate, compile, originalScope);
+            el = parentDiv.find('textarea');
+            var characterCount = parentDiv.find('.character-countdown');
+            originalScope.hideTextArea = false;
+            originalScope.$apply();
+            expect(el.is(':visible'), 'textarea').to.be.false;
+            expect(characterCount.is(':visible'), 'character countdown').to.be.false;
```
Comment (megalord) [inline src/rxCharacterCount/rxCharacterCount.spec.js]: When you set `hideTextArea` to `false`, I would think the the test should expect the element to be visible.  Am I missing something here?

Comment (parlarjb) [inline src/rxCharacterCount/rxCharacterCount.spec.js]: hmmm.... wtf.... I'll look into it

**Comment by comeatmebro** [comment]
[Wraith UI diff](http://eb4d4842ea70055541c8-b6a3ba129b5eb76af13f4d17e4c1a53b.r51.cf5.rackcdn.com/856/gallery.html)

File: src/rxCharacterCount/rxCharacterCount.spec.js [hunk 3]
```diff
@@ -120,6 +122,44 @@ describe('rxCharacterCount', function () {
...
+            parentDiv = helpers.createDirective(ngShowTemplate, compile, originalScope);
+            el = parentDiv.find('textarea');
+            var characterCount = parentDiv.find('.character-countdown');
+            originalScope.showTextArea = false;
+            originalScope.$apply();
+            expect(el.hasClass('ng-hide'), 'textarea').to.be.true;
+            expect(characterCount.hasClass('ng-hide'), 'character countdown').to.be.true;
+        });
+        
+        it('should hide the character count if the element hides (ngHide)', function () {
```
Comment (megalord) [inline src/rxCharacterCount/rxCharacterCount.spec.js]: After the changes made in the last commit, this description is not quite accurate.  Maybe something like,
`'should show the character count if the element becomes visible (ngHide)'`

**Comment by megalord** [comment]
LGTM

**Comment by comeatmebro** [comment]
[Wraith UI diff](http://eb4d4842ea70055541c8-b6a3ba129b5eb76af13f4d17e4c1a53b.r51.cf5.rackcdn.com/856/gallery.html)

File: src/rxCharacterCount/rxCharacterCount.js [hunk 4]
```diff
@@ -1,12 +1,32 @@
...
+    var extraDirectives = function (attrs) {
+        var extra = '';
+        if (_.has(attrs, 'ngShow')) {
+            extra += 'ng-show="' + attrs.ngShow + '" ';
+        }
+        if (_.has(attrs, 'ngHide')) {
+            extra += 'ng-hide="' + attrs.ngHide + '" ';
+        }
+        return extra;
+    };
```
Comment (CITguy) [inline src/rxCharacterCount/rxCharacterCount.js]: How does this scale with additional angular attribute directives? What if I used `ng-when` to show/hide the element/directive?

Comment (CITguy) [inline src/rxCharacterCount/rxCharacterCount.js]: We can do our due diligence to catch the common use cases, but I feel like we need to suggest in the documentation that if developers wish to show/hide the anchored element, they'll need to place that logic outside of the element itself.

So, instead of doing this:
```html
<textarea rx-character-count ng-show="isShown">{{someValue}}</textarea>
```

To do something like this:
```html
<span ng-show="isShown">
  <textarea rx-character-count>{{someValue}}</textarea>
</span>
```
In its current state, this directive is highly unstable and prone to little bugs like what this PR is attempting to fix.  Until it stabilizes, I suggest we document workarounds.

Comment (CITguy) [inline src/rxCharacterCount/rxCharacterCount.js]: After doing some preliminary research, we need to handle:
* `ng-if`
* `ng-show`
* `ng-hide`
* `ng-switch-when`
* `ng-switch-default`

If you handle each case in this logic, I should be good to go for this PR.

Comment (parlarjb) [inline src/rxCharacterCount/rxCharacterCount.js]: `ng-if` is handled by the `$destroy`. I'll look into the `switch` directives

Comment (parlarjb) [inline src/rxCharacterCount/rxCharacterCount.js]: The `switch` directives seem to "just work" because they appear to be using `ng-if` internally (or, at least, they're completely removing elements from the DOM, not just showing/hiding them).

**Comment by comeatmebro** [comment]
[Wraith UI diff](http://eb4d4842ea70055541c8-b6a3ba129b5eb76af13f4d17e4c1a53b.r51.cf5.rackcdn.com/856/gallery.html)

**Comment by CITguy** [comment]
DEV - LGTM

**Comment by comeatmebro** [comment]
[Wraith UI diff](http://eb4d4842ea70055541c8-b6a3ba129b5eb76af13f4d17e4c1a53b.r51.cf5.rackcdn.com/856/gallery.html)
