### PR TITLE
fix(rxFloatingHeader): rxSearchBox and rxBulkSelect fixes

### LINKED ISSUE #1038: BUG: rxBulkSelect  "Batch Actions" + rxFloatingHeader
The bulk action menu activates on scroll of a floating header.

Reproduce bug at http://rackerlabs.github.io/encore-ui/#/component/rxBulkSelect

**No floating header**
screen shot 2015-06-12 at 10 41 08 am

**Floating Header Activated - action menu should not be visible**
screen shot 2015-06-12 at 10 41 21 am
screen shot 2015-06-12 at 10 41 28 am

### LINKED ISSUE #1047: rxFloatingHeader infinite scroll
When an rxFloatingHeader table has an `rxSearchBox` in it, and the search box has focus, the page enters an "infinite scroll" mode, wherein when you scroll to the bottom of the page, it shoots you right back to the top.

### PR DESCRIPTION
**Pull request by parlarjb**
Closes #1038
Closes #1047

`rxBulkSelect` and `rxSearchBox` have their templates inserted _after_ the `rxFloatingHeader` `link` function runs. `rxFloatingHeader` needs to know about their content, so we now have them explicitly tell `rxFloatingHeader` to rerun once they're ready.

### CODE REVIEW

File: src/rxSearchBox/rxSearchBox.js [hunk 1]
```diff
@@ -24,6 +24,12 @@ angular.module('encore.ui.rxSearchBox', [])
             $scope.clearSearch = function () {
                 $scope.searchVal = '';
             };
+        },
+        link: function (scope, element, attrs, controllers) {
+            var rxFloatingHeaderCtrl = controllers[1];
+            if (!_.isUndefined(rxFloatingHeaderCtrl)) {
+                rxFloatingHeaderCtrl.update();
+            }
```
Comment (Droogans) [inline src/rxSearchBox/rxSearchBox.js]: Who thinks that any code written that utilizes features documented *at the very bottom* of https://docs.angularjs.org/guide/directive should add a comment or two?

I'm hesitant to say it should be there, since maybe I'm just not that familiar with Angular. But I will admit I googled "link function arguments" and ctrl-f'd the documentation to find out what was going on here.

Comment (parlarjb) [inline src/rxSearchBox/rxSearchBox.js]: I'm happy to add more comments, but inter-directive communication via controllers is something we've done in a few spots within the framework. It's one of the early lessons at egghead.io, so I was personally introduced to it early when learning Angular, but I don't know about others.

**Comment by CITguy** [comment]
LGTM

File: src/rxSearchBox/rxSearchBox.js (hunk 1 above)
Comment (CITguy) [inline src/rxSearchBox/rxSearchBox.js]: I've learned it through experience and osmosis.

Comment (Droogans) [inline src/rxSearchBox/rxSearchBox.js]: LGTM.

**Comment by Droogans** [comment]
LGTM
